STEM_label = "STEM"
not_STEM_label = "Not STEM"

industry_group_industry_map = {
  'Administrative Services': [
    "Archiving Service",
    "Call Center",
    "Collection Agency",
    "College Recruiting",
    "Courier Service",
    "Debt Collections",
    "Delivery",
    "Document Preparation",
    "Employee Benefits",
    "Extermination Service",
    "Facilities Support Services",
    "Housekeeping Service",
    "Human Resources",
    "Knowledge Management",
    "Office Administration",
    "Packaging Services",
    "Physical Security",
    "Project Management",
    "Staffing Agency",
    "Trade Shows",
    "Virtual Workforce"
  ],
  'Advertising': [
    "Ad Exchange",
    "Ad Network",
    "Ad Retargeting",
    "Ad Server",
    "Ad Targeting",
    "Advertising",
    "Advertising Platforms",
    "Affiliate Marketing",
    "Local Advertising",
    "Mobile Advertising",
    "Native Advertising",
    "Outdoor Advertising",
    "SEM",
    "Social Media Advertising",
    "Video Advertising"
  ],
  'Agriculture and Farming': [
    "Agriculture",
    "AgTech",
    "Animal Feed",
    "Aquaculture",
    "Equestrian",
    "Farming",
    "Forestry",
    "Horticulture",
    "Hydroponics",
    "Livestock"
  ],
  'Apps': [
    "App Discovery",
    "Apps",
    "Consumer Applications",
    "Enterprise Applications",
    "Mobile Apps",
    "Reading Apps",
    "Web Apps"
  ],
  'Artificial Intelligence (AI)': [
    "Artificial Intelligence (AI)",
    "Generative AI",
    "Intelligent Systems",
    "Machine Learning",
    "Natural Language Processing",
    "Predictive Analytics",
    "Robotic Process Automation (RPA)"
  ],
  'Biotechnology': [
    "Bioinformatics",
    "Biometrics",
    "Biopharma",
    "Biotechnology",
    "Genetics",
    "Life Science",
    "Neuroscience",
    "Quantified Self"
  ],
  'Blockchain and Cryptocurrency': [
    "Bitcoin",
    "Blockchain",
    "Cryptocurrency",
    "Decentralized Finance (DeFi)",
    "Ethereum",
    "Non-Fungible Token (NFT)",
    "Smart Contracts",
    "Web3"
  ],
  'Clothing and Apparel': [
    "Apparel",
    "Fashion",
    "Laundry and Dry-cleaning",
    "Lingerie",
    "Shoes"
  ],
  'Commerce and Shopping': [
    "Auctions",
    "Classifieds",
    "Collectibles",
    "Consumer Reviews",
    "Coupons",
    "E-Commerce",
    "E-Commerce Platforms",
    "Flash Sale",
    "Gift",
    "Gift Card",
    "Gift Exchange",
    "Gift Registry",
    "Group Buying",
    "Local Shopping",
    "Made to Order",
    "Marketplace",
    "Office Supplies",
    "Online Auctions",
    "Personalization",
    "Point of Sale",
    "Price Comparison",
    "Rental",
    "Retail",
    "Retail Technology",
    "Secondhand Goods",
    "Shopping",
    "Shopping Mall",
    "Social Shopping",
    "Sporting Goods",
    "Vending and Concessions",
    "Virtual Goods",
    "Wholesale"
  ],
  'Community and Lifestyle': [
    "Adult",
    "Baby",
    "Cannabis",
    "Children",
    "Communities",
    "Dating",
    "Elderly",
    "Family",
    "Funerals",
    "Humanitarian",
    "Leisure",
    "LGBT",
    "Lifestyle",
    "Men's",
    "Online Forums",
    "Parenting",
    "Pet",
    "Private Social Networking",
    "Professional Networking",
    "Q&A",
    "Religion",
    "Retirement",
    "Sex Industry",
    "Sex Tech",
    "Social",
    "Social Entrepreneurship",
    "Teenagers",
    "Virtual World",
    "Wedding",
    "Women's",
    "Young Adults"
  ],
  'Consumer Electronics': [
    "Computer",
    "Consumer Electronics",
    "Drones",
    "Electronics",
    "Google Glass",
    "Mobile Devices",
    "Nintendo",
    "Playstation",
    "Roku",
    "Smart Home",
    "Wearables",
    "Windows Phone",
    "Xbox"
  ],
  'Consumer Goods': [
    "Beauty",
    "Card and Board Games",
    "Cleaning Products",
    "Comics",
    "Consumer Goods",
    "Cosmetics",
    "DIY",
    "Drones",
    "Eyewear",
    "Fast-Moving Consumer Goods",
    "Flowers",
    "Furniture",
    "Green Consumer Goods",
    "Handmade",
    "Home Appliances",
    "Jewelry",
    "Lingerie",
    "Personal Care and Hygiene",
    "Shoes",
    "Tobacco",
    "Toys"
  ],
  'Content and Publishing': [
    "Blogging Platforms",
    "Books",
    "Content Delivery Network",
    "Content Discovery",
    "Content Syndication",
    "Copywriting",
    "Creative Agency",
    "DRM",
    "EBooks",
    "Journalism",
    "News",
    "Photo Editing",
    "Photo Sharing",
    "Photography",
    "Printing",
    "Publishing",
    "Social Bookmarking",
    "Video Editing",
    "Video Streaming"
  ],
  'Data and Analytics': [
    "A/B Testing",
    "Analytics",
    "Application Performance Management",
    "Artificial Intelligence (AI)",
    "Big Data",
    "Bioinformatics",
    "Biometrics",
    "Business Intelligence",
    "Consumer Research",
    "Data Collection and Labeling",
    "Data Governance",
    "Data Integration",
    "Data Management",
    "Data Mining",
    "Data Visualization",
    "Database",
    "Facial Recognition",
    "Geospatial",
    "Image Recognition",
    "Intelligent Systems",
    "Location Based Services",
    "Machine Learning",
    "Market Research",
    "Natural Language Processing",
    "Predictive Analytics",
    "Product Research",
    "Quantified Self",
    "Speech Recognition",
    "Test and Measurement",
    "Text Analytics",
    "Usability Testing"
  ],
  'Design': [
    "CAD",
    "Consumer Research",
    "Data Visualization",
    "Fashion",
    "Graphic Design",
    "Human Computer Interaction",
    "Industrial Design",
    "Interior Design",
    "Market Research",
    "Mechanical Design",
    "Product Design",
    "Product Research",
    "Usability Testing",
    "UX Design",
    "Web Design"
  ],
  'Education': [
    "Alumni",
    "Charter Schools",
    "College Recruiting",
    "Continuing Education",
    "Corporate Training",
    "E-Learning",
    "EdTech",
    "Education",
    "Edutainment",
    "Higher Education",
    "Language Learning",
    "MOOC",
    "Music Education",
    "Personal Development",
    "Primary Education",
    "Secondary Education",
    "Skill Assessment",
    "Special Education",
    "STEM Education",
    "Textbook",
    "Training",
    "Tutoring",
    "Vocational Education"
  ],
  'Energy': [
    "Battery",
    "Biofuel",
    "Biomass Energy",
    "Clean Energy",
    "Electrical Distribution",
    "Energy",
    "Energy Efficiency",
    "Energy Management",
    "Energy Storage",
    "Fossil Fuels",
    "Fuel",
    "Fuel Cell",
    "Geothermal Energy",
    "Hydroelectric",
    "Oil and Gas",
    "Power Grid",
    "Renewable Energy",
    "Solar",
    "Wind Energy"
  ],
  'Events': [
    "Concerts",
    "Event Management",
    "Event Promotion",
    "Events",
    "Nightclubs",
    "Nightlife",
    "Reservations",
    "Ticketing",
    "Wedding"
  ],
  'Financial Services': [
    "Accounting",
    "Angel Investment",
    "Asset Management",
    "Auto Insurance",
    "Banking",
    "Bitcoin",
    "Bookkeeping and Payroll",
    "Commercial Insurance",
    "Commercial Lending",
    "Consumer Lending",
    "Credit",
    "Credit Bureau",
    "Credit Cards",
    "Crowdfunding",
    "Cryptocurrency",
    "Debit Cards",
    "Debt Collections",
    "Finance",
    "Financial Exchanges",
    "Financial Services",
    "FinTech",
    "Foreign Exchange Trading",
    "Fraud Detection",
    "Funding Platform",
    "Gift Card",
    "Health Insurance",
    "Hedge Funds",
    "Impact Investing",
    "Incubators",
    "Insurance",
    "InsurTech",
    "Leasing",
    "Lending",
    "Life Insurance",
    "Micro Lending",
    "Mobile Payments",
    "Payments",
    "Personal Finance",
    "Prediction Markets",
    "Prepaid Cards",
    "Property Insurance",
    "Real Estate Investment",
    "Stock Exchanges",
    "Tax Consulting",
    "Tax Preparation",
    "Trading Platform",
    "Transaction Processing",
    "Venture Capital",
    "Virtual Currency",
    "Wealth Management"
  ],
  'Food and Beverage': [
    "Alternative Protein",
    "Bakery",
    "Brewing",
    "Cannabis",
    "Catering",
    "Coffee",
    "Confectionery",
    "Cooking",
    "Craft Beer",
    "Dairy",
    "Dietary Supplements",
    "Distillery",
    "Farmers Market",
    "Food and Beverage",
    "Food Delivery",
    "Food Processing",
    "Food Trucks",
    "Fruit",
    "Grocery",
    "Herbs and Spices",
    "Meat and Poultry",
    "Nutrition",
    "Organic Food",
    "Plant-Based Foods",
    "Recipes",
    "Restaurants",
    "Seafood",
    "Snack Food",
    "Tea",
    "Tobacco",
    "Wine And Spirits",
    "Winery"
  ],
  'Gaming': [
    "Card and Board Games",
    "Casual Games",
    "Console Games",
    "Contests",
    "Fantasy Sports",
    "Gambling",
    "Gamification",
    "Gaming",
    "MMO Games",
    "Online Games",
    "PC Games",
    "Serious Games",
    "Video Games"
  ],
  'Government and Military': [
    "CivicTech",
    "Government",
    "GovTech",
    "Law Enforcement",
    "Military",
    "National Security",
    "Politics",
    "Public Safety",
    "Social Assistance"
  ],
  'Hardware': [
    "3D Technology",
    "Application Specific Integrated Circuit (ASIC)",
    "Audio/Visual Equipment",
    "Augmented Reality",
    "Cloud Infrastructure",
    "Communication Hardware",
    "Communications Infrastructure",
    "Computer",
    "Computer Vision",
    "Consumer Electronics",
    "Data Center",
    "Data Center Automation",
    "Data Storage",
    "Drone Management",
    "Drones",
    "DSP",
    "Electronic Design Automation (EDA)",
    "Electronics",
    "Embedded Systems",
    "Field-Programmable Gate Array (FPGA)",
    "Flash Storage",
    "Google Glass",
    "GPS",
    "GPU",
    "Hardware",
    "Industrial Design",
    "Laser",
    "Lighting",
    "Mechanical Design",
    "Mobile Devices",
    "Network Hardware",
    "NFC",
    "Nintendo",
    "Optical Communication",
    "Playstation",
    "Private Cloud",
    "Remote Sensing",
    "Retail Technology",
    "RFID",
    "RISC",
    "Robotics",
    "Roku",
    "Satellite Communication",
    "Semiconductor",
    "Sensor",
    "Sex Tech",
    "Telecommunications",
    "Video Conferencing",
    "Virtual Reality",
    "Virtualization",
    "Wearables",
    "Windows Phone",
    "Wireless",
    "Xbox"
  ],
  'Health Care': [
    "Addiction Treatment",
    "Alternative Medicine",
    "Assisted Living",
    "Assistive Technology",
    "Biopharma",
    "Cannabis",
    "Child Care",
    "Clinical Trials",
    "Cosmetic Surgery",
    "Dental",
    "Diabetes",
    "Dietary Supplements",
    "Elder Care",
    "Electronic Health Record (EHR)",
    "Emergency Medicine",
    "Employee Benefits",
    "Fertility",
    "First Aid",
    "Funerals",
    "Genetics",
    "Health Care",
    "Health Diagnostics",
    "Home Health Care",
    "Hospital",
    "Medical",
    "Medical Device",
    "Mental Health",
    "mHealth",
    "Nursing and Residential Care",
    "Nutraceutical",
    "Nutrition",
    "Oncology",
    "Outpatient Care",
    "Personal Health",
    "Pharmaceutical",
    "Precision Medicine",
    "Primary and Urgent Care",
    "Psychology",
    "Rehabilitation",
    "Telehealth",
    "Therapeutics",
    "Veterinary",
    "Wellness"
  ],
  'Information Technology': [
    "Business Information Systems",
    "CivicTech",
    "Cloud Data Services",
    "Cloud Management",
    "Cloud Security",
    "CMS",
    "Contact Management",
    "CRM",
    "Cyber Security",
    "Data Center",
    "Data Center Automation",
    "Data Integration",
    "Data Mining",
    "Data Visualization",
    "DevOps",
    "Document Management",
    "E-Signature",
    "Email",
    "GovTech",
    "Identity Management",
    "Information and Communications Technology (ICT)",
    "Information Services",
    "Information Technology",
    "Intrusion Detection",
    "IT Infrastructure",
    "IT Management",
    "Management Information Systems",
    "Messaging",
    "Military",
    "Network Security",
    "Penetration Testing",
    "Private Cloud",
    "Reputation",
    "Sales Automation",
    "Scheduling",
    "Social CRM",
    "Spam Filtering",
    "Technical Support",
    "Unified Communications",
    "Video Chat",
    "Video Conferencing",
    "Virtualization",
    "VoIP"
  ],
  'Internet Services': [
    "Cloud Computing",
    "Cloud Data Services",
    "Cloud Infrastructure",
    "Cloud Management",
    "Cloud Storage",
    "Darknet",
    "Domain Registrar",
    "E-Commerce Platforms",
    "Ediscovery",
    "Email",
    "Internet",
    "Internet of Things",
    "ISP",
    "Location Based Services",
    "Messaging",
    "Music Streaming",
    "Online Forums",
    "Online Portals",
    "Private Cloud",
    "Product Search",
    "Search Engine",
    "SEM",
    "Semantic Search",
    "Semantic Web",
    "SEO",
    "SMS",
    "Social Media",
    "Social Media Management",
    "Social Network",
    "Unified Communications",
    "Vertical Search",
    "Video Chat",
    "Video Conferencing",
    "Visual Search",
    "VoIP",
    "Web Browsers",
    "Web Hosting",
    "Web3"
  ],
  'Lending and Investments': [
    "Angel Investment",
    "Banking",
    "Commercial Lending",
    "Consumer Lending",
    "Credit",
    "Credit Cards",
    "Financial Exchanges",
    "Funding Platform",
    "Hedge Funds",
    "Impact Investing",
    "Incubators",
    "Micro Lending",
    "Stock Exchanges",
    "Trading Platform",
    "Venture Capital"
  ],
  'Manufacturing': [
    "3D Printing",
    "Advanced Materials",
    "Foundries",
    "Industrial",
    "Industrial Automation",
    "Industrial Engineering",
    "Industrial Manufacturing",
    "Machinery Manufacturing",
    "Manufacturing",
    "Paper Manufacturing",
    "Plastics and Rubber Manufacturing",
    "Textiles",
    "Wood Processing"
  ],
  'Media and Entertainment': [
    "Advice",
    "Animation",
    "Art",
    "Audio",
    "Audiobooks",
    "Blogging Platforms",
    "Books",
    "Broadcasting",
    "Celebrity",
    "Concerts",
    "Content",
    "Content Creators",
    "Content Discovery",
    "Content Syndication",
    "Creative Agency",
    "Digital Entertainment",
    "Digital Media",
    "DRM",
    "EBooks",
    "Edutainment",
    "Event Management",
    "Event Promotion",
    "Events",
    "Film",
    "Film Distribution",
    "Film Production",
    "Guides",
    "In-Flight Entertainment",
    "Independent Music",
    "Internet Radio",
    "Journalism",
    "Media and Entertainment",
    "Metaverse",
    "Motion Capture",
    "Music",
    "Music Education",
    "Music Label",
    "Music Streaming",
    "Music Venues",
    "Musical Instruments",
    "News",
    "Nightclubs",
    "Nightlife",
    "Performing Arts",
    "Photo Editing",
    "Photo Sharing",
    "Photography",
    "Podcast",
    "Printing",
    "Publishing",
    "Reservations",
    "Social Media",
    "Social News",
    "Theatre",
    "Ticketing",
    "TV",
    "TV Production",
    "Video",
    "Video Editing",
    "Video on Demand",
    "Video Streaming",
    "Virtual World"
  ],
  'Messaging and Telecommunications': [
    "Email",
    "Meeting Software",
    "Messaging",
    "SMS",
    "Unified Communications",
    "Video Chat",
    "Video Conferencing",
    "VoIP",
    "Wired Telecommunications"
  ],
  'Mobile': [
    "Android",
    "Google Glass",
    "iOS",
    "mHealth",
    "Mobile",
    "Mobile Apps",
    "Mobile Devices",
    "Mobile Payments",
    "Windows Phone",
    "Wireless"
  ],
  'Music and Audio': [
    "Audio",
    "Audio Recording and Production",
    "Audio/Visual Equipment",
    "Audiobooks",
    "Independent Music",
    "Internet Radio",
    "Music",
    "Music Education",
    "Music Label",
    "Music Streaming",
    "Musical Instruments",
    "Podcast"
  ],
  'Natural Resources': [
    "Biofuel",
    "Biomass Energy",
    "Fossil Fuels",
    "Mineral",
    "Mining",
    "Mining Technology",
    "Natural Resources",
    "Oil and Gas",
    "Precious Metals",
    "Solar",
    "Timber",
    "Water",
    "Wind Energy"
  ],
  'Navigation and Mapping': [
    "Geospatial",
    "GPS",
    "Indoor Positioning",
    "Location Based Services",
    "Mapping Services",
    "Navigation"
  ],
  'Other': [
    "Alumni",
    "Association",
    "B2B",
    "B2C",
    "Blockchain",
    "Charity",
    "Collaboration",
    "Collaborative Consumption",
    "Commercial",
    "Consumer",
    "Crowdsourcing",
    "Customer Service",
    "Desktop Apps",
    "Emerging Markets",
    "Enterprise",
    "Ethereum",
    "Franchise",
    "Freemium",
    "Generation Y",
    "Generation Z",
    "Homeless Shelter",
    "Infrastructure",
    "Knowledge Management",
    "LGBT",
    "Millennials",
    "Non Profit",
    "Peer to Peer",
    "Product Management",
    "Professional Services",
    "Project Management",
    "Real Time",
    "Retirement",
    "Service Industry",
    "Sharing Economy",
    "Small and Medium Businesses",
    "Social Bookmarking",
    "Social Impact",
    "Subscription Service",
    "Technical Support",
    "Underserved Children",
    "Universities"
  ],
  'Payments': [
    "Billing",
    "Bitcoin",
    "Credit Cards",
    "Cryptocurrency",
    "Debit Cards",
    "Fraud Detection",
    "Mobile Payments",
    "Payments",
    "Transaction Processing",
    "Virtual Currency"
  ],
  'Platforms': [
    "Android",
    "Facebook",
    "Google",
    "Google Glass",
    "iOS",
    "Linux",
    "macOS",
    "Nintendo",
    "Operating Systems",
    "Playstation",
    "Roku",
    "Tizen",
    "Twitter",
    "WebOS",
    "Windows",
    "Windows Phone",
    "Xbox"
  ],
  'Privacy and Security': [
    "Cloud Security",
    "Corrections Facilities",
    "Cyber Security",
    "DRM",
    "E-Signature",
    "Fraud Detection",
    "Homeland Security",
    "Identity Management",
    "Intrusion Detection",
    "Law Enforcement",
    "Network Security",
    "Penetration Testing",
    "Physical Security",
    "Privacy",
    "Security"
  ],
  'Professional Services': [
    "Accounting",
    "Advocacy",
    "Business Development",
    "Career Planning",
    "Compliance",
    "Consulting",
    "Customer Service",
    "Employment",
    "Environmental Consulting",
    "Field Support",
    "Freelance",
    "Innovation Management",
    "Intellectual Property",
    "Legal",
    "Legal Tech",
    "Management Consulting",
    "Outsourcing",
    "Professional Networking",
    "Quality Assurance",
    "Recruiting",
    "Risk Management",
    "Social Recruiting",
    "Translation Service"
  ],
  'Real Estate': [
    "Architecture",
    "Building Maintenance",
    "Building Material",
    "Commercial Real Estate",
    "Construction",
    "Coworking",
    "Facility Management",
    "Fast-Moving Consumer Goods",
    "Green Building",
    "Heating, Ventilation, and Air Conditioning (HVAC)",
    "Home and Garden",
    "Home Decor",
    "Home Improvement",
    "Home Renovation",
    "Home Services",
    "Interior Design",
    "Janitorial Service",
    "Landscaping",
    "Mortgage",
    "Property Development",
    "Property Management",
    "PropTech",
    "Real Estate",
    "Real Estate Brokerage",
    "Real Estate Investment",
    "Rental Property",
    "Residential",
    "Self-Storage",
    "Smart Building",
    "Smart Cities",
    "Smart Home",
    "Timeshare",
    "Vacation Rental"
  ],
  'Sales and Marketing': [
    "Advertising",
    "Affiliate Marketing",
    "App Discovery",
    "App Marketing",
    "Brand Marketing",
    "Cause Marketing",
    "Content Marketing",
    "CRM",
    "Digital Marketing",
    "Digital Signage",
    "Direct Marketing",
    "Direct Sales",
    "Email Marketing",
    "Lead Generation",
    "Lead Management",
    "Local",
    "Local Advertising",
    "Local Business",
    "Loyalty Programs",
    "Marketing",
    "Marketing Automation",
    "Mobile Advertising",
    "Multi-level Marketing",
    "Outdoor Advertising",
    "Personal Branding",
    "Public Relations",
    "Sales",
    "Sales Automation",
    "Sales Enablement",
    "SEM",
    "SEO",
    "Social CRM",
    "Social Media Advertising",
    "Social Media Management",
    "Social Media Marketing",
    "Sponsorship",
    "Video Advertising"
  ],
  'Science and Engineering': [
    "Advanced Materials",
    "Aerospace",
    "Artificial Intelligence (AI)",
    "Bioinformatics",
    "Biometrics",
    "Biopharma",
    "Biotechnology",
    "Chemical",
    "Chemical Engineering",
    "Civil Engineering",
    "Embedded Systems",
    "Environmental Engineering",
    "Human Computer Interaction",
    "Industrial Automation",
    "Industrial Engineering",
    "Intelligent Systems",
    "Laser",
    "Life Science",
    "Marine Technology",
    "Mechanical Engineering",
    "Nanotechnology",
    "Neuroscience",
    "Nuclear",
    "Quantum Computing",
    "Robotics",
    "Semiconductor",
    "Software Engineering",
    "STEM Education"
  ],
  'Social Impact': [
    "Advocacy",
    "Charity",
    "Homeless Shelter",
    "Humanitarian",
    "Non Profit",
    "Social Entrepreneurship",
    "Social Impact",
    "Underserved Children"
  ],
  'Software': [
    "3D Technology",
    "Android",
    "App Discovery",
    "Application Performance Management",
    "Apps",
    "Artificial Intelligence (AI)",
    "Augmented Reality",
    "Billing",
    "Bitcoin",
    "Browser Extensions",
    "Business Process Automation (BPA)",
    "CAD",
    "Chatbot",
    "Cloud Computing",
    "Cloud Management",
    "CMS",
    "Computer Vision",
    "Consumer Applications",
    "Consumer Software",
    "Contact Management",
    "CRM",
    "Cryptocurrency",
    "Data Center Automation",
    "Data Integration",
    "Data Storage",
    "Data Visualization",
    "Database",
    "Developer APIs",
    "Developer Platform",
    "Developer Tools",
    "DevOps",
    "Document Management",
    "Drone Management",
    "E-Learning",
    "EdTech",
    "Electronic Design Automation (EDA)",
    "Embedded Software",
    "Embedded Systems",
    "Enterprise Applications",
    "Enterprise Resource Planning (ERP)",
    "Enterprise Software",
    "Facial Recognition",
    "File Sharing",
    "IaaS",
    "Image Recognition",
    "iOS",
    "Linux",
    "Machine Learning",
    "macOS",
    "Marketing Automation",
    "Meeting Software",
    "Metaverse",
    "Mobile Apps",
    "Mobile Payments",
    "MOOC",
    "Natural Language Processing",
    "Open Source",
    "Operating Systems",
    "PaaS",
    "Predictive Analytics",
    "Presentation Software",
    "Presentations",
    "Private Cloud",
    "Productivity Tools",
    "QR Codes",
    "Reading Apps",
    "Retail Technology",
    "Robotic Process Automation (RPA)",
    "Robotics",
    "SaaS",
    "Sales Automation",
    "Scheduling",
    "Sex Tech",
    "Simulation",
    "SNS",
    "Social CRM",
    "Software",
    "Software Engineering",
    "Speech Recognition",
    "Task Management",
    "Text Analytics",
    "Transaction Processing",
    "Video Conferencing",
    "Virtual Assistant",
    "Virtual Currency",
    "Virtual Desktop",
    "Virtual Goods",
    "Virtual Reality",
    "Virtual World",
    "Virtualization",
    "Web Apps",
    "Web Browsers",
    "Web Development"
  ],
  'Sports': [
    "American Football",
    "Baseball",
    "Basketball",
    "Boating",
    "Cricket",
    "Cycling",
    "Diving",
    "eSports",
    "Fantasy Sports",
    "Fitness",
    "Golf",
    "Hockey",
    "Hunting",
    "Motorsports",
    "Outdoors",
    "Racing",
    "Recreation",
    "Rugby",
    "Sailing",
    "Skiing",
    "Soccer",
    "Sporting Goods",
    "Sports",
    "Sports Leagues and Teams",
    "Surfing",
    "Swimming",
    "Table Tennis",
    "Tennis",
    "Ultimate Frisbee",
    "Volley Ball"
  ],
  'Sustainability': [
    "Biofuel",
    "Biomass Energy",
    "Carbon Capture",
    "Clean Energy",
    "CleanTech",
    "Energy Efficiency",
    "Environmental Engineering",
    "Geothermal Energy",
    "Green Building",
    "Green Consumer Goods",
    "GreenTech",
    "Hydroelectric",
    "Natural Resources",
    "Organic",
    "Pollution Control",
    "Recycling",
    "Renewable Energy",
    "Solar",
    "Sustainability",
    "Waste Management",
    "Water Purification",
    "Wildlife Conservation",
    "Wind Energy"
  ],
  'Transportation': [
    "Air Transportation",
    "Automotive",
    "Autonomous Vehicles",
    "Car Sharing",
    "Charging Infrastructure",
    "Courier Service",
    "Delivery Service",
    "Electric Vehicle",
    "Ferry Service",
    "Fleet Management",
    "Food Delivery",
    "Freight Service",
    "Last Mile Transportation",
    "Limousine Service",
    "Logistics",
    "Marine Transportation",
    "Parking",
    "Ports and Harbors",
    "Procurement",
    "Public Transportation",
    "Railroad",
    "Recreational Vehicles",
    "Ride Sharing",
    "Same Day Delivery",
    "Shipping",
    "Shipping Broker",
    "Space Travel",
    "Supply Chain Management",
    "Taxi Service",
    "Transportation",
    "Warehouse Automation",
    "Warehousing",
    "Water Transportation"
  ],
  'Travel and Tourism': [
    "Adventure Travel",
    "Amusement Park and Arcade",
    "Business Travel",
    "Casino",
    "Hospitality",
    "Hotel",
    "Museums and Historical Sites",
    "Parks",
    "Resorts",
    "Timeshare",
    "Tour Operator",
    "Tourism",
    "Travel",
    "Travel Accommodations",
    "Travel Agency",
    "Vacation Rental"
  ],
  'Video': [
    "Animation",
    "Broadcasting",
    "Film",
    "Film Distribution",
    "Film Production",
    "Motion Capture",
    "TV",
    "TV Production",
    "Video",
    "Video Editing",
    "Video on Demand",
    "Video Streaming"
  ]
}

STEM_industries = [
  "Advanced Materials",
  "Aerospace",
  "Artificial Intelligence (AI)",
  "Bioinformatics",
  "Biometrics",
  "Biopharma",
  "Biotechnology",
  "Chemical",
  "Chemical Engineering",
  "Civil Engineering",
  "Embedded Systems",
  "Environmental Engineering",
  "Human Computer Interaction",
  "Industrial Automation",
  "Industrial Engineering",
  "Intelligent Systems",
  "Laser",
  "Life Science",
  "Marine Technology",
  "Mechanical Engineering",
  "Nanotechnology",
  "Neuroscience",
  "Nuclear",
  "Quantum Computing",
  "Robotics",
  "Semiconductor",
  "Software Engineering",
  "STEM Education"
]