tag_groups = [
  'Administrative Services',
  'Advertising',
  'Agriculture and Farming',
  'Apps',
  'Artificial Intelligence (AI)',
  'Biotechnology',
  'Blockchain and Cryptocurrency',
  'Clothing and Apparel',
  'Commerce and Shopping',
  'Community and Lifestyle',
  'Consumer Electronics',
  'Consumer Goods',
  'Content and Publishing',
  'Data and Analytics',
  'Design',
  'Education',
  'Energy',
  'Events',
  'Financial Services',
  'Food and Beverage',
  'Gaming',
  'Government and Military',
  'Hardware',
  'Health Care',
  'Information Technology',
  'Internet Services',
  'Lending and Investments',
  'Manufacturing',
  'Media and Entertainment',
  'Messaging and Telecommunications',
  'Mobile',
  'Music and Audio',
  'Natural Resources',
  'Navigation and Mapping',
  'Other',
  'Payments',
  'Platforms',
  'Privacy and Security',
  'Professional Services',
  'Real Estate',
  'Sales and Marketing',
  'Science and Engineering',
  'Social Impact',
  'Software',
  'Sports',
  'Sustainability',
  'Transportation',
  'Travel and Tourism',
  'Video'
]

tag_groups_science = {
  'Administrative Services': False,
  'Advertising': False,
  'Agriculture and Farming': True,
  'Apps': False,
  'Artificial Intelligence (AI)': True,
  'Biotechnology': True,
  'Blockchain and Cryptocurrency': True,
  'Clothing and Apparel': False,
  'Commerce and Shopping': False,
  'Community and Lifestyle': False,
  'Consumer Electronics': True,
  'Consumer Goods': False,
  'Content and Publishing': False,
  'Data and Analytics': True,
  'Design': False,
  'Education': False,
  'Energy': True,
  'Events': False,
  'Financial Services': False,
  'Food and Beverage': False,
  'Gaming': False,
  'Government and Military': False,
  'Hardware': True,
  'Health Care': True,
  'Information Technology': True,
  'Internet Services': False,
  'Lending and Investments': False,
  'Manufacturing': True,
  'Media and Entertainment': False,
  'Messaging and Telecommunications': True,
  'Mobile': False,
  'Music and Audio': False,
  'Natural Resources': True,
  'Navigation and Mapping': True,
  'Other': False,
  'Payments': False,
  'Platforms': False,
  'Privacy and Security': False,
  'Professional Services': False,
  'Real Estate': False,
  'Sales and Marketing': False,
  'Science and Engineering': True,
  'Social Impact': False,
  'Software': False,
  'Sports': False,
  'Sustainability': True,
  'Transportation': False,
  'Travel and Tourism': False,
  'Video': False,
}